### ISSUE TITLE
Trivia movie quotes

### ISSUE THREAD

**Issue by DPBR8** [tjallo/DiscordPyBot#3]
Make a 'trivia' function but with Meme movie quotes.

Basically you type a command; let's say !quote

the bot will then send a quote and whoever types the correct movie title in chat first wins internet points

**Comment by tjallo** [comment]
**List of movies (and quotes) wanted.**

Should we keep a permanent database or a  session db, i.e. after each restart of the bot (~weekly) there is a 'Karma reset'

**Comment by DPBR8** [comment]
Why not both? A weekly top and an all time top?
At least, if that's not too much to ask
